### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by PhrozenByte** [tworabbits/Pico-Gzip#1]
I was wondering how you've implemented this, nice and dead simple solution! I like it :+1: :smiley:

However, you should remove the `PicoParsePagesContent` dependency (i.e. remove line 38). You actually don't depend on it, as you're compressing the current page only. Furthermore you should move the contents of `onPluginsLoaded` to `onConfigLoaded`. `onPluginsLoaded` is triggered before `onConfigLoaded`, thus `$this->disabled` will never be `FALSE` if a users tries to disable the plugin in his config. This happens not until `onConfigLoaded`.

**Comment by 0x0000001c** [comment]
Thanks a lot for your feedback! I know the PicoCMS since yesterday, so apparently I am not really into it yet ;)
I moved the enabled and php extension checks, removed the `PicoParsePagesContent` dependency and tested successfully on my machine.

Cheers, Jonas

**Comment by PhrozenByte** [comment]
:+1:
